export const WECHAT_PAY_PROVIDER = 'WECHAT_PAY_JSAPI';
export const WECHAT_PAY_REFUND_PROVIDER = 'WECHAT_PAY_REFUND';
export const WECHAT_PAY_TRANSFER_PROVIDER = 'WECHAT_PAY_TRANSFER';

export const DEFAULT_PAYMENT_SWEEP_INTERVAL_MS = 60_000;
